<a href="https://colab.research.google.com/github/Arminsbss/CNN_MNIST/blob/main/CNN_MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense

In [ ]:
#==========Here we are loading the data==========
(X_train, y_train), (X_test, y_test)= mnist.load_data()
#==========Here we are reshaping the data==========
X_train= X_train.reshape((X_train.shape[0]),X_train.shape[1],X_train.shape[2],1)
X_test= X_test.reshape((X_test.shape[0]),X_test.shape[1],X_test.shape[2],1)

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
#==========Here we are checking the data after reshaping==========
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [ ]:
#==========normalizing the pixel values==========
X_train = X_train/255
X_test = X_test/255

In [ ]:
print(X_train)
print(X_test)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [ ]:
print(y_train)
print(y_test)

[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [ ]:
model = Sequential()
model.add(Conv2D(32,(3,3),activation='relu', input_shape=(28,28,1)))

In [ ]:
model.add(MaxPool2D(2,2))
#==========adding fully connected layer==========
model.add(Flatten())
model.add(Dense(100,activation='relu'))
#==========adding output layer==========
model.add(Dense(10,activation='softmax'))
#==========compile the model==========
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
#==========fitting the model==========
model.fit(X_train,y_train,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 33s 18ms/step - loss: 0.1519 - accuracy: 0.9554
Epoch 2/10
1875/1875 [==============================] - 32s 17ms/step - loss: 0.0523 - accuracy: 0.9843
Epoch 3/10
1875/1875 [==============================] - 32s 17ms/step - loss: 0.0349 - accuracy: 0.9891
Epoch 4/10
1875/1875 [==============================] - 32s 17ms/step - loss: 0.0226 - accuracy: 0.9928
Epoch 5/10
1875/1875 [==============================] - 31s 17ms/step - loss: 0.0146 - accuracy: 0.9954
Epoch 6/10
1875/1875 [==============================] - 31s 17ms/step - loss: 0.0118 - accuracy: 0.9963
Epoch 7/10
1875/1875 [==============================] - 31s 17ms/step - loss: 0.0082 - accuracy: 0.9974
Epoch 8/10
1875/1875 [==============================] - 31s 17ms/step - loss: 0.0074 - accuracy: 0.9977
Epoch 9/10
1875/1875 [==============================] - 31s 17ms/step - loss: 0.0052 - accuracy: 0.9983
Epoch 10/10
1875/1875 [==============================] - 30s 16m

In [ ]:
#==========evaluate the model==========
model.evaluate(X_test,y_test)

313/313 [==============================] - 2s 6ms/step - loss: 0.0533 - accuracy: 0.9869


[0.053348954766988754, 0.9868999719619751]